name: image_picker_for_web
description: Web platform implementation of image_picker
repository: https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker_for_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 2.1.10

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: image_picker_for_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker_platform_interface:
    git:
      url: https://github.com/tsinis/plugins/
      ref: feat/ios-camera-overlay
      path: packages/image_picker/image_picker_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
