name: image_picker_ios
description: iOS implementation of the image_picker plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.8.6+2

environment:
  sdk: ^2.14.0
  flutter: ^2.10.0

flutter:
  plugin:
    implements: image_picker
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface:
    git:
      url: https://github.com/tsinis/plugins/
      ref: feat/ios-camera-overlay
      path: packages/image_picker/image_picker_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  pigeon: any
